module.exports = {
  important: true,

  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],

  darkMode: "class",

  theme: {
    screens: {
      xs: "360px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1420px",
      "3xl": "1920px",
    },
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        lobster: ["Lobster", "cursive"],
      },
      height: {
        "4/5": "80%",
        "3/4": "75%",
        "2/3": "66.666667%",
        "3/5": "60%",
        "1/2": "50%",
        "2/5": "40%",
        "1/3": "33.333333%",
        "1/4": "25%",
        "1/5": "20%",
      },
      width: {
        "4/5": "80%",
        "3/4": "75%",
        "2/3": "66.666667%",
        "3/5": "60%",
        "1/2": "50%",
        "2/5": "40%",
        "1/3": "33.333333%",
        "1/4": "25%",
        "1/5": "20%",
      },
      minWidth: {
        "4/5": "80%",
        "3/4": "75%",
        "2/3": "66.666667%",
        "3/5": "60%",
        "1/2": "50%",
        "2/5": "40%",
        "1/3": "33.333333%",
        "1/4": "25%",
        "1/5": "20%",
      },
    },
  },

  plugins: [
    require("daisyui"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/container-queries"),
  ],

  daisyui: {
    themes: [
      {
        myDark: {
          primary: "#00ceff",
          secondary: "#b567ad",
          accent: "#418192",
          neutral: "#444442",
          "base-100": "#fff",
          "base-content": "#000",
          info: "#330f5f",
          success: "#fd509d",
          warning: "#c085df",
          error: "#ffd801",
          "--rounded-box": "1rem",
          "--rounded-btn": "4rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
          "--navbar-padding": ".5rem",
        },
        myLight: {
          primary: "#b567ad",
          secondary: "#00ceff",
          accent: "#ffd801",
          neutral: "#ffffff",
          "base-100": "#000",
          "base-content": "#fff",
          info: "#c085df",
          success: "#ffd801",
          warning: "#330f5f",
          error: "#fd509d",
          "--rounded-box": "1rem",
          "--rounded-btn": "4rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
          "--navbar-padding": ".5rem",
        },
      },
    ],
    darkTheme: "myDark",
    base: true,
    styled: true,
    utils: true,
  },
};
