import {defineDocuments, defineLocations} from 'sanity/presentation'
import {resolveHref} from '@/sanity/lib/resolveHref'

export const mainDocuments = defineDocuments([
  {
    route: '/blog/post/:slug',
    filter: `_type == "post" && slug.current == $slug`,
  },
  {
    route: '/blog/tag/:slug',
    filter: `_type == "tag" && slug.current == $slug`,
  },
])

export const locations = {
  blog: defineLocations({
    message: 'This document is used to render the blog page',
    tone: 'positive',
    locations: [{title: 'Blog', href: resolveHref('blog')}],
  }),
  post: defineLocations({
    select: {title: 'title', slug: 'slug.current'},
    resolve: (doc) => ({
      locations: [
        {
          title: doc?.title || 'Untitled',
          href: resolveHref('post', doc?.slug),
        },
      ],
    }),
  }),
  page: defineLocations({
    select: {title: 'title', slug: 'slug.current'},
    resolve: (doc) => ({
      locations: [
        {
          title: doc?.title || 'Untitled',
          href: resolveHref('tag', doc?.slug),
        },
      ],
    }),
  }),
}

// import {map} from 'rxjs'
// import resolveHref from './resolveHref'

// // Pass 'context' as the second argument
// export const resolve = (params, context) => {
//   // Set up locations for post documents
//   if (params.type === 'post') {
//     // Subscribe to the latest slug and title
//     const doc$ = context.documentStore.listenQuery(
//       `*[_id == $id][0]{slug,title}`,
//       params,
//       {perspective: 'previewDrafts'}, // returns a draft article if it exists
//     )
//     // Return a streaming list of locations
//     return doc$.pipe(
//       map((doc) => {
//         // If the document doesn't exist or have a slug, return null
//         if (!doc || !doc.slug?.current) {
//           return null
//         }
//         const href = resolveHref(params.type, doc.slug.current)
//         return {
//           locations: [
//             {
//               title: doc.title || 'Untitled',
//               href: href, // Use the href generated by resolveHref
//             },
//             {
//               title: 'Blog',
//               href: '/blog',
//             },
//           ],
//         }
//       }),
//     )
//   }
//   return null
// }
