import {
  BsTwitch,
  BsYoutube,
  BsTwitter,
  BsTiktok,
  BsInstagram,
  BsDiscord,
  BsSpotify,
} from "react-icons/bs";

export const socialMediaData = [
  {
    imageSrc: "/TwitchCard.png",
    alt: "Twitch",
    label: "Twitch",
    username: "@Sway_bae",
    icon: <BsTwitch />,
    href: "https://www.twitch.tv/sway_bae",
  },
  {
    imageSrc: "/YoutubeCard.png",
    alt: "YouTube",
    label: "YouTube",
    username: "@SwaybaeTV",
    icon: <BsYoutube />,
    href: "https://m.youtube.com/channel/UCbpQhE5NYQ05pSp_DJJQxCA",
  },
  {
    imageSrc: "/TwitterCard.png",
    alt: "Twitter",
    label: "Twitter",
    username: "@sway_baeTV",
    icon: <BsTwitter />,
    href: "https://twitter.com/sway_baetv",
  },
  {
    imageSrc: "/TikTokCard.png",
    alt: "TikTok",
    label: "TikTok",
    username: "@sway_baeTV",
    icon: <BsTiktok />,
    href: "https://www.tiktok.com/@sway_baetv",
  },
  {
    imageSrc: "/InstagramCard.png",
    alt: "Instagram",
    label: "Instagram",
    username: "@sway_baeTV",
    icon: <BsInstagram />,
    href: "https://www.instagram.com/sway_baetv",
  },
  {
    imageSrc: "/DiscordCard.png",
    alt: "Discord",
    label: "Discord",
    username: "@Sway_bae",
    icon: <BsDiscord />,
    href: "https://discord.com/invite/K73uN9k",
  },
  {
    imageSrc: "/SpotifyCard.png",
    alt: "Spotify",
    label: "Spotify",
    username: "@Swaybae",
    icon: <BsSpotify />,
    href: "https://open.spotify.com/user/31ozjeaf4ddidr2rgqunryvetrmq",
  },
];
